# Generated by Django 4.0.3 on 2023-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
