# Generated by Django 4.0.3 on 2023-06-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paybill_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
