# Generated by Django 4.0.3 on 2023-06-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_listingitem_created_at_listingitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingitem',
            name='vacancies',
            field=models.IntegerField(default=1),
        ),
    ]
