# Generated by Django 4.0.3 on 2023-07-04 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listing', '0007_listingitem_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingitem',
            name='booked_by',
            field=models.ManyToManyField(blank=True, related_name='booked_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
