# Generated by Django 4.0.3 on 2023-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_listingitem_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='booking_fee',
            field=models.IntegerField(default=1),
        ),
    ]
