# Generated by Django 4.0.3 on 2023-07-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_listingitem_booking_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingitem',
            name='booking_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='features',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingitem',
            name='vacancies',
            field=models.IntegerField(),
        ),
    ]
