# Generated by Django 4.0.3 on 2023-07-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_booking_id_booking_booking_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
