# Generated by Django 4.0.3 on 2023-07-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_listingitem_booked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='listing_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='username',
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.listingitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
