# Generated by Django 4.0.3 on 2023-07-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_booking_username_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_tenant',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
